name: libdbm
version: 0.1.6
description: A tiny and fast (1000s read/write per second) database with
  a simple API (`Map`) for Dart using disk-based hashing. No dependencies,
  batteries included.
homepage: https://github.com/libdbm/libdbm
repository: https://github.com/libdbm/libdbm
issue_tracker: https://github.com/libdbm/libdbm/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  faker: ^2.0.0-rc.1
  pedantic: ^1.11.0
  test: ^1.16.7
  collection: ^1.15.0

