name: libdbm
version: 0.1.2
description: A super small and fast (100s read/write per second) KV database for Dart using
  disk-based hashing for lookups. No dependencies.
homepage: https://github.com/libdbm/libdbm
repository: https://github.com/libdbm/libdbm
issue_tracker: https://github.com/libdbm/libdbm/issues

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:

dev_dependencies:
  faker: ^1.3.0
  pedantic: ^1.9.0
  test: ^1.14.4

